version: "3.9"

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    volumes:
      - /home/benjamin/appdata/jackett:/config
      - /mnt/media/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true
    expose:
      - 9117
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - /home/benjamin/appdata/overseerr:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    expose:
      - 5055
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - /home/benjamin/appdata/qbittorrent:/config
      - /mnt/media/downloads:/data/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    expose:
      - 8080
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /home/benjamin/appdata/radarr:/config
      - /mnt/media/:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /home/benjamin/appdata/sonarr:/config
      - /mnt/media/:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 8989
    restart: unless-stopped
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: susanoo
    volumes:
      - /home/benjamin/appdata/syncthing:/config
      - /mnt/media/movies:/data/movies
      - /mnt/media/tv:/data/tv
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 8384
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    volumes:
      - /home/benjamin/appdata/tautulli:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    expose:
      - 8181
    restart: unless-stopped

networks:
  default:
    external: true
    name: amaterasu