networks:
  default:
    external: true
    name: servarr
volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.50.4,rw,vers=4.1
      device: ":/mnt/blackbox/media"
  appdata:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.50.4,rw,vers=4.1
      device: ":/mnt/blackbox/appdata"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - /root/appdata/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9696:9696
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - /root/appdata/overseerr:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Budapest
    ports:
      - 5055:5055
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - /root/appdata/qbittorrent:/config
      - type: volume
        source: media
        target: /data/downloads
        volume:
          subpath: downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1001
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /root/appdata/radarr:/config
      - media:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1001
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /root/appdata/sonarr:/config
      - media:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1001
    ports:
      - 8989:8989
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /root/appdata/sonarr:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1001
    ports:
      - 8181:8181