version: "3.9"

services:
  cloudflare-ddns:
    image: joshava/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    volumes:
      - /home/benjamin/appdata/cloudflare-ddns/config.yaml:/app/config.yaml
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/benjamin/appdata/swag:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - URL=${DOMAIN_NAME}
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
      - DOCKER_MODS=linuxserver/mods:swag-auto-proxy|linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-f2bdiscord|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-dbip
      - DOCKER_HOST=dockerproxy
      - DISC_HOOK=${DISC_HOOK}
      - DISC_ME=${DISC_ME}
      - DISC_API=${DISC_API}
    extra_hosts:
      - ${DOMAIN_NAME}:127.0.0.1
    expose:
      - 443
      - 80
    restart: unless-stopped
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=0
    restart: unless-stopped
  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    user: "1000:1000"
    volumes:
      - /home/benjamin/appdata/authelia:/config
      - /home/benjamin/appdata/authelia/secrets:/secrets
      - /etc/localtime:/etc/localtime:ro
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/NOTIFIER_SMTP_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
    expose:
      - 9091
    restart: unless-stopped
    labels:
      - swag=enable
      - swag_url=${AUTHELIA_URL}
  authelia-redis:
    image: redis:latest
    container_name: authelia-redis
    volumes:
      - /home/benjamin/appdata/redis:/data
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 6379
    restart: unless-stopped
  authelia-db:
    image: postgres:14
    container_name: authelia-postgres
    volumes:
      - /home/benjamin/appdata/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    volumes:
      - /home/benjamin/appdata/organizr:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8080:80
    restart: unless-stopped
    labels:
      - swag=enable
      - swag_auth=authelia

networks:
  default:
    external: true
    name: amaterasu