name: "nebula-sync"

services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://192.168.50.11|${PIHOLE_1_APP_PASSWORD}
    - REPLICAS=https://192.168.50.12|${PIHOLE_2_APP_PASSWORD}
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
    - TZ=${TZ}
    - NS_DEBUG=true