name: "nebula-sync"

services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://pihole1.${TAILNET}|${PIHOLE_1_APP_PASSWORD}
    #- REPLICAS=http://ph2.example.com|password,http://ph3.example.com|password
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *

networks:
  default:
    name: caddy-net
    external: true