name: "reverse_proxy"

services:
####################
# Reverse Proxy
####################

  caddy:
    container_name: caddy
    build:
      context: ${REPODIR}/services/admin/caddy/dockerfile
      dockerfile: caddy.dockerfile # Custom build which uses cloudflare ddns
    logging:
      driver: ${LOGGING_DRIVER:-local}
    ports:
      - ${PORT_CADDY_HTTP}:80
      - ${PORT_CADDY_HTTPS}:443
      - ${PORT_CADDY_HTTPS}:443/udp
      - ${PORT_CADDY_ADMIN}:2019
    volumes:
      - ${REPODIR}/services/admin/caddy/config/Caddyfile:/etc/caddy/Caddyfile:ro # Required.
      - ${CONFIGDIR}/caddy/data:/data # Optional, house for certs. Caddy adds its own /caddy/ directory
      - ${CONFIGDIR}/caddy/config:/config # Optional, JSON Config files. Caddy adds its own /caddy/ directory
    labels:
      - homepage.group=Administration
      - homepage.name=Caddy
      - homepage.icon=caddy.svg
      - homepage.description=Reverse Proxy
      - homepage.widget.type=caddy
      - homepage.widget.url=http://${HOST_NAME}:${PORT_CADDY_ADMIN}
    environment:
      - TZ=${TZ}
      - LOG_FILE=${LOGDIR}/caddy/access.log
      - DOMAIN=${DOMAIN}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN}
      - EMAIL=${EMAIL_ADMIN}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - HOST_NAME=${HOST_NAME}
    healthcheck:
      test: ["CMD", "caddy", "version"]
    restart: unless-stopped

networks:
  default:
    name: caddy-net
    external: true