networks:
  default:
    name: caddy-net

services:
####################
# Reverse Proxy
####################

  caddy:
    container_name: caddy
    build:
      context: ./dockerfile
      dockerfile: caddy.dockerfile #Custom build which uses duckdns. Control image version in this file

    ports:
      - ${PORT_CADDY_HTTP}:80
      - ${PORT_CADDY_HTTPS}:443
      - ${PORT_CADDY_HTTPS}:443/udp
      - ${PORT_CADDY_ADMIN}:2019

    environment:
      LOG_FILE: ${LOGDIR}/caddy/access.log
      DOMAIN: ${DOMAIN}
      ADMIN_DOMAIN: ${ADMIN_DOMAIN}
      EMAIL: ${EMAIL_ADMIN}
      CF_API_TOKEN: ${CF_API_TOKEN}

    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro # Required. 
      - ${CONFIGDIR}/caddy/data:/data # Optional, house for certs. Caddy adds its own /caddy/ directory
      - ${CONFIGDIR}/caddy/config:/config # Optional, JSON Config files. Caddy adds its own /caddy/ directory

    healthcheck:
      test: ["CMD", "caddy", "version"]
    restart: unless-stopped
