global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:3003']
  - job_name: 'pve'
    static_configs:
      - targets:
        - susanoo:9221  # Proxmox VE node with PVE exporter.
        - eurus:9221
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']