global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PORT_PROMETHEUS_HTTP:-9090}']
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:${PORT_TEMPO_HTTP:-3200}' ]
  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:${PORT_CADDY_ADMIN}']
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:${PORT_NODEEXPORTER_HTTP:-9100}']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:${PORT_CADVISOR_HTTP:-3003}']