data_dir: "/var/lib/vector"

api:
  enabled: false

# Ingest data by tailing one or more files
sources:
  container_logs:
    type: "docker_logs"
    include_containers: ["caddy"]

  vector_logs:
    type: internal_logs

sinks:
  loki_vectorlogs:
    type: loki
    inputs:
      - vector_logs
    encoding:
      codec: json
    endpoint: 'http://loki:${PORT_LOKI_HTTP:-3100}'
    labels:
      logsource: vector

  loki_dockersyslog:
    type: loki
    inputs:
      - container_logs
    encoding:
      codec: json
    endpoint: 'http://loki:${PORT_LOKI_HTTP:-3100}'
    labels:
      logsource: docker