data_dir: "/var/lib/vector"

api:
  enabled: false

# Ingest data by tailing one or more files
sources:
  container_logs:
    type: docker_logs
    include_containers:
      - caddy

  vector_logs:
    type: internal_logs

sinks:
  loki_vectorlogs:
    type: loki
    inputs:
      - vector_logs
    encoding:
      codec: json
    endpoint: ${LOKI_ENDPOINT}
    labels:
      logsource: vector

  loki_container_log:
    type: loki
    inputs:
      - container_logs
    encoding:
      codec: json
    endpoint: ${LOKI_ENDPOINT}
    labels:
      logsource: docker

  print:
    type: console
    inputs:
      - vector_logs
      - container_logs
    encoding:
      codec: json