version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    device_cgroup_rules:
      - "c 189:* rmw"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/appdata/frigate/config.yml:/config/config.yml:ro
      - /mnt/media/frigate:/media/frigate:rw
      - /root/appdata/frigate/db:/db:rw
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
    environment:
      - FRIGATE_RTSP_PASSWORD
      - LIBVA_DRIVER_NAME_JELLYFIN
      - PLUS_API_KEY