name: "uptime-kuma"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ${CONFIGDIR}/uptime-kuma-data:/app/data
    ports:
      - ${PORT_UPTIME_KUMA:-3002}:3001  # <Host Port>:<Container Port>
    restart: always