networks:
  default:
    name: caddy-net
    external: true
volumes:
  appdata:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.50.4,rw,vers=4.1
      device: ":/mnt/blackbox/appdata"

services:
  actual_server:
    container_name: actual_server
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - ${PORT_ACTUAL}:5006
    volumes:
      - type: volume
        source: appdata
        target: /data
        volume:
          subpath: actual
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped