name: "monitoring"

services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - ${PORT_BESZEL_HTTP:-8090}:8090
    environment:
      - USER_CREATION=true
    volumes:
      - ${CONFDIR}/beszel_data:/beszel_data
      - ${CONFDIR}/beszel_socket:/beszel_socket